# Generated by Django 2.2.12 on 2020-05-17 18:31

from django.db import migrations

from teachers.models import Teachers

def forwards(apps, schema):
    for teacher in Teachers.objects.all().only('tech_name', 'tech_surn').iterator():
        teacher.first_name = teacher.tech_name.capitalize()
        teacher.last_name = teacher.tech_surn.capitalize()
        teacher.save(update_fields=['tech_name', 'tech_surn'])

def backwards(apps, schema):
    print('backwards')

class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teachers_tech_phone'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
