# Generated by Django 2.2.12 on 2020-05-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_empl', models.CharField(max_length=32)),
                ('group_name', models.CharField(max_length=32)),
                ('title', models.BooleanField()),
                ('info', models.CharField(max_length=255)),
            ],
        ),
    ]
