# Generated by Django 2.2.12 on 2020-05-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_phone',
            field=models.CharField(default='', max_length=24),
        ),
    ]
