# Generated by Django 2.2.12 on 2020-05-17 18:48

from django.db import migrations

from group.models import Group

def forwards(apps, schema):
    for group in Group.objects.all().only('group_empl', 'group_name').iterator():
        group.group_empl = group.group_empl.capitalize()
        group.group_name = group.group_name.capitalize()
        group.save(update_fields=['group_empl', 'group_name'])

def backwards(apps, schema):
    print('backwards')


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_group_phone'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
