# Generated by Django 2.2.12 on 2020-05-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_name', models.CharField(max_length=32)),
                ('tech_surn', models.CharField(max_length=32)),
                ('tech_gend', models.BooleanField()),
                ('tech_city', models.CharField(max_length=64)),
                ('tech_age', models.PositiveIntegerField()),
                ('tech_date', models.DateField()),
            ],
        ),
    ]
